### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by mattbishop** [pouya-eghbali/sia#2]
I am trying your interesting library out but I'm using typescript. Are you planning on adding an index.d.ts file to this project?

https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by pouya-eghbali** [comment]
I will take a look, shouldn't be very difficult, we don't have a lot of parameters or options, I'll work on it this weekend.

**Comment by pouya-eghbali** [comment]
Doing a little bit of investigation and playing around, this actually is going to take a lot of time as I'm not very experienced with TypeScript. I'll keep this open and work on it when I have time. I will accept pull requests on this.

**Comment by CEbbinghaus** [comment]
@pouya-eghbali do you have something to go off of or should any contribution be started from scratch?
