### ISSUE TITLE
Dynamic buffer size

### ISSUE THREAD

**Issue by Llorx** [pouya-eghbali/sia#5]
I've checked the code and seems that if you serialize an object bigger than the buffer size, it will throw an error.

Is possible to add a check to increase the buffer temporary for that big serialization? I want to use it in an environment where users may try to serialize a REALLY big buffer (depending on their RAM) and don't want to just allocate a lot of memory for those 0.01% cases, but also don't want to get tickets for those 0.01% cases. Maybe an option to increase the buffer by jumps of X if the maximum is reached.

**Comment by pouya-eghbali** [comment]
That makes sense to me, I'll add the feature.

**Comment by Llorx** [comment]
Nice ^^

**Comment by pouya-eghbali** [comment]
@Llorx sorry it took time, I'm almost done with the implementation, there is one little issue I need to take care of and we're done. You can check the progress on https://github.com/pouya-eghbali/sia/tree/autogrow

**Comment by Llorx** [comment]
Oh, perfect! Thank you!

**Comment by PenguinToast** [comment]
@pouya-eghbali what issues still need to be resolved? I'm happy to help out here, if it's not a huge lift.

**Comment by clhuang** [comment]
I've written an alternative implementation with a different strategy, that seems to be significantly faster: https://github.com/pouya-eghbali/sia/pull/7

**Comment by pouya-eghbali** [comment]
Closing this, solved thanks to @clhuang
